site_name: Ontology for the Anatomy of the Insect SkeletoMuscular system
theme: readthedocs
nav:
  - Getting started: index.md
  - Tour:
      - Exploring AISM: exploring.md
      - Placing AISM ontologies under AISM: obo-bridge.md
      - Using AISM: using-aism.md
      - Integration Tests: integration-tests.md
      - Editors Readme: editors.md
  - How-to guides:
      - Standard ODK workflows:
          - Overview: odk-workflows/index.md
          - Editors Workflow: odk-workflows/EditorsWorkflow.md
          - Release Workflow: odk-workflows/ReleaseWorkflow.md
          - Manage your ODK Repository: odk-workflows/RepoManagement.md
          - Setting up Docker for ODK: odk-workflows/SettingUpDockerForODK.md
          - Imports management: odk-workflows/UpdateImports.md
          - Managing the documentation: odk-workflows/ManageDocumentation.md
          - Continuous Integration: odk-workflows/ContinuousIntegration.md
          - Your ODK Repository Overview: odk-workflows/RepositoryFileStructure.md 
      - Contributing: contributing.md
  - Other:
      - Cite: cite.md
      - History: history.md
